server:
    port: 9090
# ===================================================================
# OSS 阿里云文件服务
# ===================================================================
aliyunoss:
   endpoint: http://oss-cn-shenzhen.aliyuncs.com #endpoint是访问OSS的域名。如果您已经在OSS的控制台上 创建了Bucket，请在控制台上查看域名。
   accessKeyId: LTAIK0pBab2SfZuU #accessKeyId和accessKeySecret是OSS的访问密钥，您可以在控制台上创建和查看，
   accessKeySecret: K7DlkE7f74IAkg4zVcuqCsaBpHYkuS #accessKeyId和accessKeySecret是OSS的访问密钥，您可以在控制台上创建和查看，
   idleConnectionTime: 10000





